CREATE DATABASE BDROUPAS;

USE BDROUPAS;
/*Criação da tabela produto*/
CREATE TABLE TBPRODUTO(
ID_PRODUTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_PRODUTO VARCHAR(10) NOT NULL,
PRECO_PRODUTO DECIMAL(5,2),
COR_PRODUTO VARCHAR(10) NOT NULL,
TAMANHO_PRODUTO VARCHAR(3) NOT NULL,
DESCRICAO_PRODUTO VARCHAR(20),
ESTOQUE_PRODUTO INT NOT NULL
);
/*Criação da tabela cliente*/
CREATE TABLE TBCLIENTE(
ID_CLIENTE INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOME_CLIENTE VARCHAR(40) NOT NULL,
CPF_CLIENTE VARCHAR(15),
TELEFONE_CLIENTE VARCHAR(14) NOT NULL,
EMAIL_CLIENTE VARCHAR(30)
);
/*Criação da table venda*/
CREATE TABLE TBVENDA(
ID_VENDA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
COD_CLIENTE INT NOT NULL,
VENDEDOR VARCHAR(15) NOT NULL,
DATA_VENDA DATE,
FOREIGN KEY (COD_CLIENTE) REFERENCES TBCLIENTE(ID_CLIENTE)
)ENGINE=INNODB;

/*Criação da tabela produtos vendidos*/
CREATE TABLE TBPRODUTOSVENDIDOS(
ID_PRODUTO_VENDIDO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
COD_PROD INT NOT NULL,
COD_VENDA INT NOT NULL,
QTD_VENDIDO INT NOT NULL,
FOREIGN KEY (COD_PROD) REFERENCES TBPRODUTO(ID_PRODUTO),
FOREIGN KEY (COD_VENDA) REFERENCES TBVENDA(ID_VENDA)
)ENGINE=INNODB; 

/*Inserindo produto "calça cargo preta"*/
INSERT INTO TBPRODUTO(NOME_PRODUTO,PRECO_PRODUTO,COR_PRODUTO,TAMANHO_PRODUTO,DESCRICAO_PRODUTO,ESTOQUE_PRODUTO)
VALUES('Calça carg',120,'preto','G','Calça de bom tecido',30); 

/*Inserindo produto "camiseta cinza"*/
INSERT INTO TBPRODUTO(NOME_PRODUTO,PRECO_PRODUTO,COR_PRODUTO,TAMANHO_PRODUTO,DESCRICAO_PRODUTO,ESTOQUE_PRODUTO)
VALUES('Camiseta',70,'Cinza','M','Tecido confortável',20);

/*Inserindo produto "Meia das guerreiras do KPOP"*/
INSERT INTO TBPRODUTO(NOME_PRODUTO,PRECO_PRODUTO,COR_PRODUTO,TAMANHO_PRODUTO,DESCRICAO_PRODUTO,ESTOQUE_PRODUTO)
VALUES('Meia kpop',20,'Colorida',32,'Tamanho do 22 ao 32',30);

/*Inserindo produto "moletom" azul*/
INSERT INTO TBPRODUTO(NOME_PRODUTO,PRECO_PRODUTO,COR_PRODUTO,TAMANHO_PRODUTO,DESCRICAO_PRODUTO,ESTOQUE_PRODUTO)
VALUES('Moletom',100,'Azul','G','Tecido não desbota',20);

/*Inserindo produto "Jaqueta" branca*/
INSERT INTO TBPRODUTO(NOME_PRODUTO,PRECO_PRODUTO,COR_PRODUTO,TAMANHO_PRODUTO,DESCRICAO_PRODUTO,ESTOQUE_PRODUTO)
VALUES('Jaqueta',120,'Branca','M','Jaquete de couro',15);

/*Inserindo Clientes*/
INSERT INTO TBCLIENTE(NOME_CLIENTE,CPF_CLIENTE,TELEFONE_CLIENTE,EMAIL_CLIENTE)
VALUES('Amara Ketlen','335.283.977-99','(17)996646174','amaraketlen2@gmail.com');

INSERT INTO TBCLIENTE(NOME_CLIENTE,CPF_CLIENTE,TELEFONE_CLIENTE,EMAIL_CLIENTE)
VALUES('Julia Amaral','487.672.258-09','(17)996834722','juliaamaral3@gmail.com');

INSERT INTO TBCLIENTE(NOME_CLIENTE,CPF_CLIENTE,TELEFONE_CLIENTE,EMAIL_CLIENTE)
VALUES('Nicolas','754.358.648-67','(17)996572960','nicolasr3@gmail.com');

INSERT INTO TBCLIENTE(NOME_CLIENTE,CPF_CLIENTE,TELEFONE_CLIENTE,EMAIL_CLIENTE)
VALUES('Maria Beatriz','485.981.267-06','(17)998420651','beatrizmaria7@gmail.com');

INSERT INTO TBCLIENTE(NOME_CLIENTE,CPF_CLIENTE,TELEFONE_CLIENTE,EMAIL_CLIENTE)
VALUES('João Pedro','581.364.891-47','(17)996472209','joaozinho67@gmail.com');

/*Inserindo vendas*/
INSERT INTO TBVENDA(COD_CLIENTE,VENDEDOR,DATA_VENDA)
VALUES(1,'Mathias','2026/04/15');

INSERT INTO TBVENDA(COD_CLIENTE,VENDEDOR,DATA_VENDA)
VALUES(2,'Suelen','2026/04/18');

INSERT INTO TBVENDA(COD_CLIENTE,VENDEDOR,DATA_VENDA)
VALUES(3,'Domenica','2026/04/22');

/*Inserindo produtos vendidos*/
/*Na venda 1, produto 2 e 4*/
INSERT INTO TBPRODUTOSVENDIDOS(COD_PROD,COD_VENDA,QTD_VENDIDO)
VALUES(2,1,2),
      (4,1,1);
/*Na venda 2, produto 2*/
INSERT INTO TBPRODUTOSVENDIDOS(COD_PROD,COD_VENDA,QTD_VENDIDO)
VALUES(1,2,3);
/*Na venda 3, produto 1 e 3*/
INSERT INTO TBPRODUTOSVENDIDOS(COD_PROD,COD_VENDA,QTD_VENDIDO)
VALUES(1,3,2),
      (3,3,1);
      
